### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by guyvo** [damienpontifex/opencl-in-action-swift#1]
Hey Damien,

Great initiative ! I just tried to compile your examples in Xcode Version 6.4 (6E35b) running on OSX public beta ElCap. It seems there are a few problems maybe due the fact I'm still under swift 1.2 as i'm not in the apple development program.

Matvec:

opencl-in-action-swift-master/Ch1/MatVec/MatVec/main.swift:41:17: Cannot invoke 'gcl_malloc' with an argument list of type '(UInt, inout [(cl_float)], UInt64)'

opencl-in-action-swift-master/Ch1/MatVec/MatVec/main.swift:42:17: Cannot invoke 'gcl_malloc' with an argument list of type '(UInt, inout [(cl_float)], UInt64)'

opencl-in-action-swift-master/Ch1/MatVec/MatVec/main.swift:43:17: Cannot invoke 'gcl_malloc' with an argument list of type '(UInt, nil, UInt64)'

DeviceExt:

opencl-in-action-swift-master/Ch2/DeviceExtTest/DeviceExtTest/main.swift:26:18: Expected expression in list of expressions

opencl-in-action-swift-master/Ch2/DeviceExtTest/DeviceExtTest/main.swift:23:2: Cannot invoke 'clGetDeviceInfo' with an argument list of type '(cl_device_id, UInt32, UInt, inout UInt32, nil)'

opencl-in-action-swift-master/Ch2/DeviceExtTest/DeviceExtTest/main.swift:23:17: Expected an argument list of type '(cl_device_id, cl_device_info, Int, UnsafeMutablePointer<Void>, UnsafeMutablePointer<Int>)'

opencl-in-action-swift-master/Ch2/DeviceExtTest/DeviceExtTest/main.swift:26:97: Expected ',' separator

**Comment by damienpontifex** [comment]
I haven't worked on this in a while, so with the rapid changes in Swift, it's most likely a few data types that are invalid in the method calls.

I will have a look today and fix any build issues for Swift 1.2

**Comment by damienpontifex** [comment]
@guyvo let me know how those changes go (now pushed into master)

I did have one issue where the project failed to find `matvec.cl.h` in the bridging header. I believe it isn't generated until the end of the build. Had to comment out that line and the call to the kernel to get it to build and then uncomment now that they were generated and build worked fine.

Still to test functionality, this is just working build for now

**Comment by guyvo** [comment]
Thanks I will try them out. Concerning the build of the bridging header I had the same problem. You have to force building when clicking on the header file and choose compile that seems to do the trick. But that has nothing to do with swift on itself I noticed it before with another project in C. Maybe with Xcode 7 Apple will do some improvements regarding the OpenCL DEV and make it even more easier.

**Comment by guyvo** [comment]
@damienpontifex 

Compile is OK now in swift 1.2
I also tried to execute it on the GPU changing line with conditional compile:

#if FOR_GPU
    let queue = gcl_create_dispatch_queue(cl_queue_flags(CL_DEVICE_TYPE_GPU), nil)
#else
    let queue = gcl_create_dispatch_queue(cl_queue_flags(CL_DEVICE_TYPE_CPU), nil)
#endif

This works also. Be aware that #define in swift code is not possible but you can create a custom flag in the swift compiler section like -D FOR_GPU

Maybe interesting to take this into your next examples.

-G
